[project]
authors = ["Rabeez Riaz <ruoter123@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ds_learning"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
lab = "jupyter lab"
nvim = "nvim"

[dependencies]
python = ">=3.13.3,<3.14"
numpy = ">=2.2.4,<3"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.1,<4"
scipy = ">=1.15.2,<2"
tqdm = ">=4.67.1,<5"
jupyter = ">=1.1.1,<2"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.6,<9"
seaborn = ">=0.13.2,<0.14"
